### PR TITLE
Add 404 error return

### PR DESCRIPTION
**Pull request by MemeHoovy**
title, this was me attempting to code and make a PR for a C# project
idk if this works because **I have no way to test it**

### CODE REVIEW

**Comment by MistressPlague** [comment]
lol

**Comment by MistressPlague** [comment]
This is not needed at all, as anything can be sent from client --> server and vice versa. It is not for modifying to your needs. You use it elsewhere, including handling.

**Comment by MemeHoovy** [comment]
okay, there's really no need to get savage

**Comment by MistressPlague** [comment]
That wasn't my intent. My intent was to be direct and to logically respond. Sorry if I came off that way.

**Comment by MemeHoovy** [comment]
yeah, it's fine

**Comment by MistressPlague** [comment]
If ya need any assistance, or just want to hang out, hmu at Kanna#0002

**Comment by MemeHoovy** [comment]
alright 👍🏻

**Pull request closed without merging**
